import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import {getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {getFirestore,doc,collection,onSnapshot,setDoc,deleteDoc,getDocs} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
const $=id=>document.getElementById(id), MAX_ORIGINAL=20*1024*1024, MAX_DATA=620000;
let auth,db,user=null,profile={name1:'',name2:'',start:'',cover:''},events=[],offProfile=null,offEvents=null,pendingCover='',currentPhoto='';
const message=e=>({ 'auth/email-already-in-use':'อีเมลนี้มีบัญชีแล้ว','auth/invalid-email':'รูปแบบอีเมลไม่ถูกต้อง','auth/invalid-credential':'อีเมลหรือรหัสผ่านไม่ถูกต้อง','auth/weak-password':'รหัสผ่านสั้นเกินไป','auth/operation-not-allowed':'ยังไม่ได้เปิด Email/Password ใน Firebase Authentication','auth/unauthorized-domain':'ยังไม่ได้เพิ่มโดเมนเว็บใน Firebase Authorized domains','auth/invalid-api-key':'ค่า Firebase API key ไม่ถูกต้อง','auth/network-request-failed':'เชื่อมต่อ Firebase ไม่สำเร็จ ตรวจสอบอินเทอร์เน็ต','permission-denied':'Firestore ปฏิเสธการเข้าถึง: เปิด Firebase Console → Firestore Database → Rules แล้ววางกฎจาก firestore.rules และกด Publish','failed-precondition':'ยังไม่ได้สร้าง Firestore Database ใน Firebase Console','unavailable':'เชื่อมต่อ Firestore ไม่ได้ ตรวจสอบอินเทอร์เน็ตและสถานะฐานข้อมูล'}[e.code]||e.message||'เกิดข้อผิดพลาด');
try{if(firebaseConfig.apiKey.startsWith('PASTE_')||firebaseConfig.projectId.startsWith('PASTE_')||firebaseConfig.appId.startsWith('PASTE_'))throw Error('ยังไม่ได้ตั้งค่า Firebase: เปิดไฟล์ firebase-config.js แล้วใส่ค่าจาก Firebase Console จากนั้นอัปโหลดโฟลเดอร์ขึ้น Netlify อีกครั้ง');let app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app)}catch(e){$('authError').textContent=message(e)}
function syncError(err){let box=$('syncError');box.textContent=err?message(err):'';box.classList.toggle('hidden',!err)}
const parse=s=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return null;let [y,m,d]=s.split('-').map(Number),v=new Date(y,m-1,d,12);return v.getFullYear()===y&&v.getMonth()===m-1&&v.getDate()===d?v:null},today=()=>{let n=new Date();return new Date(n.getFullYear(),n.getMonth(),n.getDate(),12)},fmt=d=>new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'long',year:'numeric'}).format(d),days=(a,b)=>Math.round((Date.UTC(b.getFullYear(),b.getMonth(),b.getDate())-Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()))/86400000),anniv=(s,y,m)=>new Date(y,m,Math.min(s.getDate(),new Date(y,m+1,0).getDate()),12);
const profileRef=()=>doc(db,'users',user.uid,'profile','data'),eventRef=id=>doc(db,'users',user.uid,'events',id);
function render(){let s=parse(profile.start),n=today();$('coupleName').textContent=[profile.name1,profile.name2].filter(Boolean).join(' ♡ ')||'เรื่องราวของเรา';$('couplePhoto').classList.toggle('hidden',!profile.cover);if(profile.cover)$('couplePhoto').src=profile.cover;else $('couplePhoto').removeAttribute('src');$('days').textContent=s?(days(s,n)>=0?`${days(s,n)+1} วัน`:'ยังไม่ถึงวันเริ่มคบ'):'ตั้งค่าวันเริ่มคบ';$('startLabel').textContent=s?'เริ่มต้น '+fmt(s):'กดตั้งค่าเพื่อเริ่มต้น';$('count').textContent=events.length+' รายการ';if(s){updateSurprise(s,n);let months=(n.getFullYear()-s.getFullYear())*12+n.getMonth()-s.getMonth(),c=anniv(s,s.getFullYear(),s.getMonth()+Math.max(1,months));while(c<n){months++;c=anniv(s,s.getFullYear(),s.getMonth()+Math.max(1,months))}let total=(c.getFullYear()-s.getFullYear())*12+c.getMonth()-s.getMonth();$('next').textContent=total%12===0?`${total/12} ปี`:`${total} เดือน`;$('nextDate').textContent=fmt(c)+(days(n,c)===0?' • วันนี้':` • อีก ${days(n,c)} วัน`)}else{$('next').textContent='—';$('nextDate').textContent='ตั้งค่าวันเริ่มคบก่อน';$('surpriseBtn').classList.add('hidden')}let q=$('search').value.trim().toLowerCase(),list=events.filter(e=>[e.title,e.place,e.note].some(x=>(x||'').toLowerCase().includes(q))).sort((a,b)=>$('sort').value==='new'?b.date.localeCompare(a.date):a.date.localeCompare(b.date));$('events').replaceChildren();if(!list.length){let p=document.createElement('div');p.className='empty';p.textContent=q?'🔎 ไม่พบความทรงจำที่ค้นหา':'💌 ยังไม่มีความทรงจำ ลองเพิ่มเรื่องราวแรกของเรากัน';$('events').append(p)}for(let e of list){let card=document.createElement('article');card.className='card event';card.style.setProperty('--stagger',Math.min($('events').childElementCount,8)*55+'ms');if(e.photo){let im=document.createElement('img');im.src=e.photo;im.alt=e.title;card.append(im)}let h=document.createElement('h3');h.textContent=e.title;card.append(h);let meta=document.createElement('div');meta.className='muted small';meta.textContent=fmt(parse(e.date))+(e.place?' • '+e.place:'');card.append(meta);if(e.note){let p=document.createElement('p');p.textContent=e.note;card.append(p)}let actions=document.createElement('div');actions.className='row';for(let [label,action,cls] of [['แก้ไข','edit','secondary'],['ลบ','delete','danger']]){let b=document.createElement('button');b.className=cls;b.textContent=label;b.dataset.id=e.id;b.dataset.action=action;actions.append(b)}card.append(actions);$('events').append(card)}}
function anniversaryMonths(s,n){let months=(n.getFullYear()-s.getFullYear())*12+n.getMonth()-s.getMonth();return months>0 && anniv(s,n.getFullYear(),n.getMonth()).getTime()===n.getTime()?months:0}
function updateSurprise(s,n){let months=anniversaryMonths(s,n);$('surpriseBtn').classList.toggle('hidden',!months);if(!months||!user)return;let key=`our-days-surprise-${user.uid}-${n.getFullYear()}-${n.getMonth()+1}-${n.getDate()}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');setTimeout(()=>showSurprise(months),500)}
function showSurprise(months){if(!months)return;$('surpriseTitle').textContent=months%12===0?`สุขสันต์วันครบรอบ ${months/12} ปี!`:`สุขสันต์วันครบรอบ ${months} เดือน!`;$('surpriseText').textContent=[profile.name1,profile.name2].filter(Boolean).join(' ♡ ')||'เรื่องราวของเรา';$('surpriseDialog').showModal();if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<36;i++){let h=document.createElement('span');h.className='surprise-confetti';h.textContent=['♥','♡','✦','🌸'][i%4];h.style.setProperty('--x',(i*97%100)+'%');h.style.setProperty('--size',(16+i%5*5)+'px');h.style.setProperty('--duration',(2.5+i%6*.25)+'s');h.style.setProperty('--delay',(i%8*.1)+'s');h.style.setProperty('--drift',((i%7-3)*24)+'px');document.body.append(h);setTimeout(()=>h.remove(),5000)}}
$('surpriseBtn').onclick=()=>showSurprise(anniversaryMonths(parse(profile.start),today()));$('surpriseClose').onclick=()=>$('surpriseDialog').close();
function previewCover(){$('coverPreview').classList.toggle('hidden',!pendingCover);$('removeCover').classList.toggle('hidden',!pendingCover);if(pendingCover)$('coverPreview').src=pendingCover;else $('coverPreview').removeAttribute('src')}
async function preparePhoto(file){if(file.size>MAX_ORIGINAL)throw Error('ไฟล์ต้นฉบับต้องไม่เกิน 20 MB');if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw Error('รองรับ JPG, PNG, WebP และ GIF');let url=URL.createObjectURL(file);try{let img=new Image();img.src=url;await img.decode();if(!img.naturalWidth)throw Error('อ่านรูปภาพไม่สำเร็จ');let base=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight));for(let i=0;i<8;i++){let canvas=document.createElement('canvas'),scale=base*Math.pow(.81,Math.max(0,i-1));canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));let ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);let data=canvas.toDataURL('image/jpeg',Math.max(.46,.79-i*.05));if(data.length<MAX_DATA)return data}throw Error('รูปใหญ่เกินไป ลองเลือกรูปอื่น')}finally{URL.revokeObjectURL(url)}}
$('authForm').onsubmit=async e=>{e.preventDefault();if(!auth){$('authError').textContent='ตั้งค่า Firebase ก่อน จึงจะเข้าสู่ระบบได้';return}$('authError').textContent='กำลังเข้าสู่ระบบ…';try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(err){$('authError').textContent=message(err)}};
$('logoutBtn').onclick=()=>signOut(auth);
if(auth)onAuthStateChanged(auth,u=>{offProfile?.();offEvents?.();user=u;profile={name1:'',name2:'',start:'',cover:''};events=[];syncError(null);$('authError').textContent='';$('authScreen').classList.toggle('hidden',!!u);$('appScreen').classList.toggle('hidden',!u);if(!u)return;offProfile=onSnapshot(profileRef(),snap=>{profile={name1:'',name2:'',start:'',cover:'',...snap.data()};render()},err=>syncError(err));offEvents=onSnapshot(collection(db,'users',u.uid,'events'),snap=>{events=snap.docs.map(d=>({id:d.id,...d.data()}));render()},err=>syncError(err))});
$('settingsBtn').onclick=()=>{for(let key of ['name1','name2','start'])$(key).value=profile[key]||'';pendingCover=profile.cover||'';$('coverInput').value='';previewCover();$('settingsError').textContent='';$('settingsDialog').showModal()};$('removeCover').onclick=()=>{pendingCover='';$('coverInput').value='';previewCover()};$('coverInput').onchange=async()=>{let f=$('coverInput').files[0];if(!f)return;try{pendingCover=await preparePhoto(f);previewCover()}catch(e){alert(message(e));$('coverInput').value=''}};
$('settingsForm').onsubmit=async e=>{e.preventDefault();if(!parse($('start').value))return;let button=$('settingsSave');button.disabled=true;button.textContent='กำลังบันทึก…';$('settingsError').textContent='';try{await setDoc(profileRef(),{name1:$('name1').value.trim().slice(0,50),name2:$('name2').value.trim().slice(0,50),start:$('start').value,cover:pendingCover});$('settingsDialog').close();syncError(null)}catch(err){syncError(err);$('settingsError').textContent='บันทึกไม่สำเร็จ: '+message(err)}finally{button.disabled=false;button.textContent='บันทึก'}};
$('addBtn').onclick=()=>{$('eventForm').reset();$('eventId').value='';$('date').value=new Date().toLocaleDateString('en-CA');$('eventHeading').textContent='เพิ่มกิจกรรม';$('photoStatus').textContent='';currentPhoto='';$('eventDialog').showModal()};document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('photo').onchange=async()=>{let f=$('photo').files[0];if(!f)return;try{currentPhoto=await preparePhoto(f);$('photoStatus').textContent='เพิ่มรูปแล้ว • ระบบปรับขนาดรูปให้'}catch(err){alert(message(err));$('photo').value=''}};
$('eventForm').onsubmit=async e=>{e.preventDefault();if(!parse($('date').value))return;let id=$('eventId').value||crypto.randomUUID(),entry={title:$('title').value.trim().slice(0,100),date:$('date').value,place:$('place').value.trim().slice(0,100),note:$('note').value.trim().slice(0,4000),photo:currentPhoto};if(!entry.title)return;try{await setDoc(eventRef(id),entry);$('eventDialog').close();syncError(null);celebrate()}catch(err){syncError(err);alert('บันทึกไม่สำเร็จ: '+message(err))}};
$('events').onclick=async e=>{let b=e.target.closest('button[data-action]');if(!b)return;let item=events.find(x=>x.id===b.dataset.id);if(!item)return;if(b.dataset.action==='delete'){if(!confirm(`ลบกิจกรรม “${item.title}” หรือไม่?`))return;try{await deleteDoc(eventRef(item.id))}catch(err){alert('ลบไม่สำเร็จ: '+message(err))}}else{$('eventForm').reset();$('eventHeading').textContent='แก้ไขกิจกรรม';for(let key of ['title','date','place','note'])$(key).value=item[key]||'';$('eventId').value=item.id;currentPhoto=item.photo||'';$('photoStatus').textContent=currentPhoto?'มีรูปเดิมอยู่ เลือกรูปใหม่เพื่อเปลี่ยน':'';$('eventDialog').showModal()}};
$('search').oninput=render;$('sort').onchange=render;
$('exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify({...profile,events},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='our-days-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('importInput').onchange=async e=>{let file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw Error('ไฟล์สำรองต้องไม่เกิน 20 MB');let raw=JSON.parse(await file.text());if(!raw||!Array.isArray(raw.events)||raw.events.length>100||typeof raw.start!=='string'||raw.start&&!parse(raw.start))throw Error('ไฟล์สำรองไม่ถูกต้อง');if(!confirm('นำเข้าจะเพิ่มกิจกรรมจากไฟล์ และแทนชื่อ วันที่เริ่มคบ กับรูปคู่ ดำเนินการต่อหรือไม่?'))return;let cover=raw.cover||'';if(cover.length>=MAX_DATA){if(!/^data:image\/(png|jpeg|webp|gif);base64,/.test(cover))throw Error('รูปคู่ไม่ถูกต้อง');cover=await preparePhoto(await (await fetch(cover)).blob())}await setDoc(profileRef(),{name1:String(raw.name1||'').slice(0,50),name2:String(raw.name2||'').slice(0,50),start:raw.start,cover});let count=0;for(let x of raw.events){if(typeof x.title!=='string'||!parse(x.date)||typeof x.photo!=='string')continue;let photo=x.photo;if(photo.length>=MAX_DATA){if(!/^data:image\/(png|jpeg|webp|gif);base64,/.test(photo))continue;photo=await preparePhoto(await (await fetch(photo)).blob())}await setDoc(eventRef(crypto.randomUUID()),{title:x.title.slice(0,100),date:x.date,place:String(x.place||'').slice(0,100),note:String(x.note||'').slice(0,4000),photo});count++}alert(`นำเข้าสำเร็จ ${count} รายการ`)}catch(err){alert('นำเข้าไม่สำเร็จ: '+message(err))}finally{e.target.value=''}};
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<9;i++){let h=document.createElement('span');h.className='heart-burst';h.textContent=i%3?'♥':'♡';h.style.setProperty('--size',(20+i%4*7)+'px');h.style.setProperty('--delay',(i*55)+'ms');h.style.left=(32+i*4.5)+'%';h.style.top=(54+i%3*4)+'%';document.body.append(h);setTimeout(()=>h.remove(),2000)}}
